Fetch new quotes on 15s timer
zerodao-finance/zeroBRIDGE pull request #193
Opened 2022-06-17 18:28 UTC by kmkhami

2022-06-17 18:33 UTC, mitche50 approved these changes

2022-06-18 15:45 UTC, mitche50 requested changes
Fix cleanup

2022-06-20 04:48 UTC, yoyobojo approved these changes

2022-06-20 04:56 UTC, yoyobojo commented
Why did adding a stateful `setInterval` fix the issue?? The normal `clearInterval` is not being hit in the return

2022-06-20 05:02 UTC, merged